# SPDX-FileCopyrightText: 2021 Alliander N.V.
#
# SPDX-License-Identifier: Apache-2.0

name: 'OSPO License scan action'
description: 'A GitHub Action to scan for licenses in your code.'
inputs:
  report-formats:
    description: |
      Desired output formats for the `ort report -f` command, provided in a comma-separated format.
      For example 'SpdxDocument,WebApp'.
      Documentation at https://github.com/oss-review-toolkit/ort/#user-content-reporter
    required: false
    default: 'SpdxDocument,WebApp'
  run-download:
    description: |
      Boolean value which determines whether the ORT Download step should run
    required: false
    default: false
  run-evaluate:
    description: |
      Boolean value which determines whether the ORT Evaluate step should run
    required: false
    default: true
  run-report:
    description: |
      Boolean value which determines whether the ORT Report step should run
    required: false
    default: true
  run-scan:
    description: |
      Boolean value which determines whether the ORT Scan step should run
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '--report-formats'
    - ${{ inputs.report-formats }}
    - '--run-download'
    - ${{ inputs.run-download }}
    - '--run-evaluate'
    - ${{ inputs.run-evaluate }}
    - '--run-report'
    - ${{ inputs.run-report }}
    - '--run-scan'
    - ${{ inputs.run-scan }}
